akka {
  loglevel = "INFO"
  # Enruta el logging de Akka a SLF4J/Logback
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

  actor {
    # Dispatcher por defecto: pool de hilos para ejecutar los actores.
    default-dispatcher {
      type = "Dispatcher"
      executor = "fork-join-executor"
      fork-join-executor {
        parallelism-min = 2
        parallelism-factor = 2.0
        parallelism-max = 8
      }
    }
  }
}
